"""Android MCP Server (android-device) — v0.7.0-alpha.

FastMCP server bridging an LLM agent to one or more Android devices via ADB.
Mirrors the architecture of win-device / mac-device (state model, FastMCP,
streamable-http on Tailscale, advisory per-device holder coordination), with
platform-specific tools for touch / keys / app management / shell-on-device.

Multi-device support (v0.7.0-alpha):
- All 25 tools accept an optional `device` parameter (serial or alias).
- Alias map is loaded from `~/.agent-fleet/android-aliases.json` at startup
  (auto-generated by the setup wizard or `setup_aliases.py`).
- Two new session-level tools: `set_default_device` / `get_default_device`.
- If `device` is omitted and exactly one phone is connected, it is selected
  automatically. Multiple phones with no `device` raises MultipleDevicesError.
- `acquire` / `release` / `get_status` are per-device.
- FastMCP `instructions=` reports the connected-device list at MCP handshake.
- Resource `androidfleet://devices` provides a live JSON snapshot.

Transport: streamable-http on 0.0.0.0:8768/mcp.

Connection mode (USB / Wireless / Hybrid) is the operator's choice at
host-setup time; the server itself is mode-agnostic and only requires
that `adb devices` shows the target devices.

ADB binary resolution order:
  1. ATB_ANDROID_ADB env var (absolute path)
  2. `adb` on PATH
  3. Known SDK locations (Win: %LOCALAPPDATA%\\Android\\Sdk\\platform-tools)
  4. Error if not found.
"""

from __future__ import annotations

import io
import os
import platform as host_platform
import shutil
import subprocess
import sys
import threading
from pathlib import Path
from typing import Annotated, Any, Optional

from PIL import Image as PILImage
from pydantic import Field

from fastmcp import Context, FastMCP
from fastmcp.utilities.types import Image

# _aliases / _device_state are shared across platform servers — see platforms/common/
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "common"))

from _aliases import DeviceInfo, derive_alias, load_aliases, resolve_aliases
from _device_state import DeviceStateRegistry


# ============================================================
#                    ADB BINARY RESOLUTION
# ============================================================

def _resolve_adb() -> str:
    if env := os.environ.get("ATB_ANDROID_ADB"):
        if Path(env).is_file():
            return env
    if path := shutil.which("adb"):
        return path
    candidates = [
        Path(os.environ.get("LOCALAPPDATA", "")) / "Android" / "Sdk" / "platform-tools" / "adb.exe",
        Path.home() / "Library" / "Android" / "sdk" / "platform-tools" / "adb",
        Path("/opt/homebrew/bin/adb"),
        Path("/usr/local/bin/adb"),
        Path("/usr/bin/adb"),
    ]
    for c in candidates:
        if c.is_file():
            return str(c)
    raise FileNotFoundError(
        "adb not found. Set ATB_ANDROID_ADB=/path/to/adb or install platform-tools."
    )


_ADB = _resolve_adb()

# fastmcp/mcp lib has an open task-cancel-vs-respond race on streamable-http
# (jlowin/fastmcp#823, #508): any tool call exceeding ~30s crashes the entire
# MCP session. We hard-cap subprocess timeout here at 25s (leaving 5s margin)
# regardless of what the caller requests. Callers that legitimately need long
# adb ops (install_app, push_file, pull_file) still pass their original
# timeout — it's preserved in the return dict as `requested_timeout` for
# diagnostics, and an `effective_timeout` field shows what we actually used.
# A planned start_process-based async API will replace the long-path callers
# (see backlog).
_FASTMCP_DEADLINE_SAFE_SECONDS = 25


def _adb_run(args: list[str], timeout: int = 30, capture_bytes: bool = False, serial: str | None = None) -> dict:
    """Run an adb command with timeout. Returns dict with stdout/stderr/returncode.

    capture_bytes=True returns raw bytes in 'stdout_bytes' (for screencap).
    serial: when provided, prepends ["-s", serial] to the adb args.

    Note: subprocess timeout is hard-capped at _FASTMCP_DEADLINE_SAFE_SECONDS.
    On timeout, return dict adds `timed_out=True, requested_timeout, effective_timeout, hint`.
    """
    if serial:
        cmd = [_ADB, "-s", serial] + args
    else:
        cmd = [_ADB] + args
    effective_timeout = min(timeout, _FASTMCP_DEADLINE_SAFE_SECONDS)
    try:
        proc = subprocess.run(
            cmd,
            timeout=effective_timeout,
            capture_output=True,
        )
    except subprocess.TimeoutExpired as e:
        partial_stdout_bytes = e.stdout if isinstance(e.stdout, bytes) else b""
        partial_stderr_bytes = e.stderr if isinstance(e.stderr, bytes) else b""
        clamp_note = (
            f"adb command timed out after {effective_timeout}s "
            f"(caller requested {timeout}s; clamped to fastmcp-safe deadline; see jlowin/fastmcp#823)"
        )
        out: dict = {
            "returncode": -1,
            "stderr": (partial_stderr_bytes.decode("utf-8", errors="replace") + ("\n" if partial_stderr_bytes else "") + clamp_note),
            "stdout_bytes": partial_stdout_bytes if capture_bytes else b"",
            "timed_out": True,
            "requested_timeout": timeout,
            "effective_timeout": effective_timeout,
            "hint": "Long adb ops (large APK install, big file push/pull) currently exceed the safe transport deadline. Workarounds: split into chunks, or wait for the start_process-based async install/push API.",
        }
        if capture_bytes:
            out["stdout"] = ""
        else:
            out["stdout"] = partial_stdout_bytes.decode("utf-8", errors="replace")
        return out
    out = {
        "returncode": proc.returncode,
        "stderr": proc.stderr.decode("utf-8", errors="replace"),
    }
    if capture_bytes:
        out["stdout_bytes"] = proc.stdout
        out["stdout"] = ""
    else:
        out["stdout"] = proc.stdout.decode("utf-8", errors="replace")
    return out


def _adb_shell(cmd: str, timeout: int = 30, capture_bytes: bool = False, serial: str | None = None) -> dict:
    """`adb shell <cmd>`. Convenience wrapper.

    serial: when provided, targets the specified device via -s.
    """
    if capture_bytes:
        return _adb_run(["exec-out"] + cmd.split(), timeout=timeout, capture_bytes=True, serial=serial)
    return _adb_run(["shell", cmd], timeout=timeout, serial=serial)


_DIAG_FIELDS = ("timed_out", "requested_timeout", "effective_timeout", "hint")


def _diag(r: dict) -> dict:
    """Pick optional timeout-diagnostic fields from an _adb_run / _adb_shell result.
    Returns empty dict on success (no timeout)."""
    return {k: r[k] for k in _DIAG_FIELDS if k in r}


# ============================================================
#               MULTI-DEVICE: DETECTION + ALIASES
# ============================================================

class MultipleDevicesError(RuntimeError):
    """Raised when a tool can't pick a device automatically and the caller didn't specify one."""


ALIAS_CONFIG_PATH = Path.home() / ".agent-fleet" / "android-aliases.json"


def _detect_devices() -> list[DeviceInfo]:
    """Enumerate authorized devices via `adb devices -l` + per-device getprop.

    For each authorized serial:
      - pull `model:<x>` from the `-l` trailing metadata when adb supplied it
      - run `getprop ro.product.brand` (5s timeout each)
      - fall back to `getprop ro.product.model` when `-l` didn't include it

    Returns devices sorted by serial. Empty list is a valid return.
    """
    r = _adb_run(["devices", "-l"], timeout=10)
    if r["returncode"] != 0:
        raise RuntimeError(f"adb devices -l failed: {r['stderr']}")

    parsed: list[tuple[str, str | None]] = []  # (serial, model_from_-l_or_None)
    for ln in r["stdout"].splitlines():
        if not ln.strip() or ln.startswith("List of devices"):
            continue
        parts = ln.split()
        # Authorized only: state must literally be "device"
        if len(parts) >= 2 and parts[1] == "device":
            serial = parts[0]
            model = None
            for kv in parts[2:]:
                if kv.startswith("model:"):
                    model = kv[len("model:"):]
                    break
            parsed.append((serial, model))

    out: list[DeviceInfo] = []
    for serial, model in parsed:
        # brand via getprop
        br = _adb_run(["-s", serial, "shell", "getprop", "ro.product.brand"], timeout=5)
        brand = br["stdout"].strip() if br["returncode"] == 0 else ""
        brand = brand or None

        if model is None:
            mr = _adb_run(["-s", serial, "shell", "getprop", "ro.product.model"], timeout=5)
            if mr["returncode"] == 0:
                model = mr["stdout"].strip() or None

        out.append(DeviceInfo(serial=serial, brand=brand, model=model))

    out.sort(key=lambda d: d.serial)
    return out


def _load_alias_overrides() -> dict[str, str]:
    """Load alias overrides; missing/empty file → {}. Malformed → warn + {}."""
    try:
        return load_aliases(ALIAS_CONFIG_PATH)
    except Exception as e:  # noqa: BLE001 - warn + degrade
        print(
            f"[android-device] WARNING: failed to load alias overrides from "
            f"{ALIAS_CONFIG_PATH}: {e}",
            file=sys.stderr,
        )
        return {}


# ============================================================
#                 PER-DEVICE HOLDER REGISTRY
# ============================================================

_state_registry = DeviceStateRegistry()


# ============================================================
#                  SESSION-STICKY DEFAULT DEVICE
# ============================================================

# FastMCP 3.3.1 exposes `Context.session_id` which is per-session for
# streamable-http transport (a generated UUID for others). It can raise
# RuntimeError if no session is available — we guard for that.

_session_defaults: dict[str, str] = {}
_session_defaults_lock = threading.Lock()
_FALLBACK_SESSION_KEY = "__no_session__"  # used when ctx.session_id is unavailable


def _session_key(ctx: Optional[Context]) -> str:
    if ctx is None:
        return _FALLBACK_SESSION_KEY
    try:
        return ctx.session_id
    except Exception:
        return _FALLBACK_SESSION_KEY


def _get_session_default(ctx: Optional[Context]) -> Optional[str]:
    key = _session_key(ctx)
    with _session_defaults_lock:
        return _session_defaults.get(key)


def _set_session_default(ctx: Optional[Context], serial: Optional[str]) -> None:
    key = _session_key(ctx)
    with _session_defaults_lock:
        if serial is None:
            _session_defaults.pop(key, None)
        else:
            _session_defaults[key] = serial


# ============================================================
#                     DEVICE RESOLVER
# ============================================================

def _format_known(detected: list[DeviceInfo], aliases: dict[str, str]) -> str:
    """Human-readable list of available devices for error messages."""
    if not detected:
        return "(no devices attached)"
    bits = []
    for d in detected:
        alias = aliases.get(d.serial, "?")
        bits.append(f"{alias} ({d.serial})")
    return ", ".join(bits)


def _resolve_device(
    device_arg: Optional[str],
    session_default: Optional[str] = None,
) -> str:
    """Pick a serial. Lookup order:

      1. device_arg matches a detected serial → return it
      2. device_arg matches a resolved alias  → return that serial
      3. (else) session_default → recurse with device_arg=session_default
      4. (else) detected has exactly 1 phone → return it
      5. else → raise MultipleDevicesError
    """
    detected = _detect_devices()
    overrides = _load_alias_overrides()
    aliases = resolve_aliases(detected, overrides)

    if device_arg:
        serials = {d.serial for d in detected}
        if device_arg in serials:
            return device_arg
        for serial, alias in aliases.items():
            if alias == device_arg:
                return serial
        known = _format_known(detected, aliases)
        raise RuntimeError(
            f"unknown device '{device_arg}'. Known: {known}"
        )

    if session_default:
        # Recurse with the sticky default — but the device may have vanished;
        # the recursive call will raise a clear "unknown device" error in that case.
        return _resolve_device(session_default, session_default=None)

    if len(detected) == 1:
        return detected[0].serial

    if not detected:
        raise MultipleDevicesError(
            "no devices found. Plug an authorized Android device via USB or pair via Wireless Debugging."
        )

    known = _format_known(detected, aliases)
    raise MultipleDevicesError(
        f"multiple devices attached ({len(detected)}). "
        f"Pass device=<alias|serial>, or call set_default_device() to set a session sticky default. "
        f"Available: {known}"
    )


# ============================================================
#               FASTMCP SERVER + INSTRUCTIONS
# ============================================================

def _build_instructions() -> str:
    """One-shot snapshot of detected devices for the FastMCP initialize handshake.

    Best-effort: silently degrades to a static no-devices message if detection fails.
    """
    try:
        detected = _detect_devices()
        overrides = _load_alias_overrides()
        aliases = resolve_aliases(detected, overrides)
    except Exception:
        detected, aliases = [], {}

    if not detected:
        return (
            "Android MCP bridge (multi-device).\n"
            "\n"
            "No devices currently attached. Plug a phone via USB and accept the "
            "'Allow USB debugging' prompt (or pair via Wireless Debugging), then "
            "call list_devices() to discover them."
        )

    if len(detected) == 1:
        d = detected[0]
        alias = aliases.get(d.serial, d.serial)
        return (
            f"Android MCP bridge (multi-device). 1 device attached:\n"
            f"  - {alias}  ({d.serial}, {d.brand or '?'} {d.model or '?'})\n"
            f"\n"
            f"Only one device is attached, so tools auto-route to it — you can "
            f"omit the `device` parameter. Call list_devices() to refresh."
        )

    lines = [f"Android MCP bridge (multi-device). {len(detected)} devices attached:"]
    for d in detected:
        alias = aliases.get(d.serial, d.serial)
        lines.append(f"  - {alias}  ({d.serial}, {d.brand or '?'} {d.model or '?'})")
    lines.append("")
    lines.append(
        "Multiple devices attached — every tool call must target one explicitly. Options:"
    )
    lines.append("  - Pass `device=<alias|serial>` to each tool call, OR")
    lines.append(
        "  - Call set_default_device(device='<alias|serial>') once to set a sticky default "
        "for THIS session — subsequent tool calls without `device` will route there."
    )
    lines.append("Use list_devices() to refresh the live list at any time.")
    return "\n".join(lines)


mcp = FastMCP("android-device", instructions=_build_instructions())


@mcp.tool
def acquire(
    device: Annotated[
        Optional[str],
        Field(description="serial or alias; omit if only 1 phone or you've set a default"),
    ] = None,
    holder_name: Annotated[
        str,
        Field(description="Human-readable identifier (e.g. 'agent-A', 'qjl-laptop')"),
    ] = "anonymous",
    ctx: Context = None,
) -> dict:
    """Claim exclusive use of an Android device. Advisory only — tools still work for others."""
    serial = _resolve_device(device, _get_session_default(ctx))
    result = _state_registry.acquire(serial, holder_name)
    result["device"] = serial
    return result


@mcp.tool
def release(
    device: Annotated[
        Optional[str],
        Field(description="serial or alias; omit if only 1 phone or you've set a default"),
    ] = None,
    holder_name: Annotated[
        str,
        Field(description="Must match the name used in acquire"),
    ] = "anonymous",
    ctx: Context = None,
) -> dict:
    """Release the exclusive-use claim. Only the current holder can release."""
    serial = _resolve_device(device, _get_session_default(ctx))
    result = _state_registry.release(serial, holder_name)
    result["device"] = serial
    return result


@mcp.tool
def get_status(
    device: Annotated[
        Optional[str],
        Field(description="serial or alias; omit if only 1 phone or you've set a default"),
    ] = None,
    ctx: Context = None,
) -> dict:
    """Show whether the specified device is currently claimed and by whom."""
    serial = _resolve_device(device, _get_session_default(ctx))
    result = _state_registry.status(serial)
    result["device"] = serial
    return result


# ============================================================
#                     DEVICE INFO
# ============================================================

def _build_devices_snapshot(ctx: Optional[Context] = None) -> dict:
    """Shared implementation for list_devices() and the devices_resource()."""
    detected = _detect_devices()
    overrides = _load_alias_overrides()
    aliases = resolve_aliases(detected, overrides)
    holders = _state_registry.all_status()
    session_default_serial = _get_session_default(ctx) if ctx is not None else None

    out = []
    for d in detected:
        h = holders.get(d.serial)
        out.append({
            "serial": d.serial,
            "alias": aliases.get(d.serial),
            "brand": d.brand,
            "model": d.model,
            "in_use": h is not None,
            "holder": h["holder"] if h else None,
            "default_for_session": (
                ctx is not None and session_default_serial == d.serial
            ),
        })

    return {"count": len(out), "devices": out}


@mcp.tool
def list_devices(ctx: Context = None) -> dict:
    """List ALL attached Android devices with alias, model, brand, and holder status.

    Returns {"count": int, "devices": [{"serial", "alias", "brand", "model",
    "in_use", "holder", "default_for_session"}, ...]}.

    `default_for_session` is True for the serial currently set as this
    session's sticky default (via set_default_device()); False otherwise.

    Always reflects current state — re-runs adb on every call.
    """
    return _build_devices_snapshot(ctx)


@mcp.tool
def set_default_device(
    device: Annotated[
        str,
        Field(description="serial or alias to use as the default for this session"),
    ],
    ctx: Context = None,
) -> dict:
    """Set a sticky default device for THIS MCP session.

    Subsequent tool calls without an explicit `device` param will route to
    this serial. Use list_devices() to see available options. Pass an empty
    string or call with the same value to update; there is no explicit clear
    operation in this version.

    Returns {"set": True, "device": <serial>, "alias": <alias>}.
    """
    serial = _resolve_device(device, None)
    _set_session_default(ctx, serial)
    overrides = _load_alias_overrides()
    aliases = resolve_aliases(_detect_devices(), overrides)
    return {"set": True, "device": serial, "alias": aliases.get(serial)}


@mcp.tool
def get_default_device(ctx: Context = None) -> dict:
    """Return the sticky default device for this session, if any.

    Returns {"device": <serial> | None, "alias": <alias> | None}.
    """
    serial = _get_session_default(ctx)
    if serial is None:
        return {"device": None, "alias": None}
    overrides = _load_alias_overrides()
    aliases = resolve_aliases(_detect_devices(), overrides)
    return {"device": serial, "alias": aliases.get(serial)}


@mcp.resource("androidfleet://devices")
def devices_resource() -> dict:
    """Live snapshot of all attached Android devices (re-queries adb on every read).

    Same shape as list_devices(), but without session context — the
    `default_for_session` field will always be False here.
    """
    return _build_devices_snapshot(ctx=None)


@mcp.tool
def get_screen_size(
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Return the device screen resolution as reported by `wm size`."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_shell("wm size", timeout=5, serial=serial)
    if r["returncode"] != 0:
        return {"error": r["stderr"], **_diag(r)}
    # Format: "Physical size: 1080x2340"  (sometimes also "Override size: 720x1560")
    width = height = None
    for line in r["stdout"].splitlines():
        if ":" in line and "x" in line:
            try:
                v = line.split(":", 1)[1].strip()
                w, h = v.split("x")
                width, height = int(w), int(h)
            except (ValueError, IndexError):
                continue
    if width is None:
        return {"error": "could not parse wm size", "raw": r["stdout"]}
    return {"width": width, "height": height, "raw": r["stdout"].strip()}


# ============================================================
#                       SCREEN
# ============================================================

@mcp.tool
def take_screenshot(
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> Image:
    """Capture the device screen and return as PNG.

    Uses `adb exec-out screencap -p`, which dumps a PNG to stdout. Resilient
    to OEM locked-down ROMs since it doesn't require pushing any APK.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_run(["exec-out", "screencap", "-p"], timeout=15, capture_bytes=True, serial=serial)
    if r["returncode"] != 0 or not r["stdout_bytes"]:
        # Some Huawei ROMs won't `exec-out` cleanly; fall back to push-then-pull
        return _take_screenshot_fallback(serial=serial)
    raw = r["stdout_bytes"]
    if not raw.startswith(b"\x89PNG"):
        return _take_screenshot_fallback(serial=serial)
    return Image(data=raw, format="png")


def _take_screenshot_fallback(serial: str | None = None) -> Image:
    """Fallback: write to /sdcard, pull, read."""
    remote = "/sdcard/atb_screenshot.png"
    r1 = _adb_shell(f"screencap -p {remote}", timeout=10, serial=serial)
    if r1["returncode"] != 0:
        raise RuntimeError(f"screencap failed: {r1['stderr']}")
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tf:
        local_path = tf.name
    r2 = _adb_run(["pull", remote, local_path], timeout=15, serial=serial)
    if r2["returncode"] != 0:
        raise RuntimeError(f"adb pull failed: {r2['stderr']}")
    _adb_shell(f"rm {remote}", timeout=5, serial=serial)
    raw = Path(local_path).read_bytes()
    Path(local_path).unlink(missing_ok=True)
    return Image(data=raw, format="png")


# ============================================================
#                       TOUCH
# ============================================================

@mcp.tool
def tap(
    x: Annotated[int, Field(ge=0, description="X coordinate in screen pixels")],
    y: Annotated[int, Field(ge=0, description="Y coordinate in screen pixels")],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Tap the screen at (x, y). Coordinates are in the same space as get_screen_size."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_shell(f"input tap {x} {y}", timeout=5, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], **_diag(r)}
    return {"ok": True, "x": x, "y": y}


@mcp.tool
def swipe(
    x1: Annotated[int, Field(ge=0, description="Start X")],
    y1: Annotated[int, Field(ge=0, description="Start Y")],
    x2: Annotated[int, Field(ge=0, description="End X")],
    y2: Annotated[int, Field(ge=0, description="End Y")],
    duration_ms: Annotated[int, Field(ge=50, le=10000, description="Swipe duration in ms")] = 300,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Swipe from (x1,y1) to (x2,y2) over duration_ms milliseconds."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_shell(f"input swipe {x1} {y1} {x2} {y2} {duration_ms}", timeout=15, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], **_diag(r)}
    return {"ok": True, "from": (x1, y1), "to": (x2, y2), "duration_ms": duration_ms}


@mcp.tool
def long_press(
    x: int,
    y: int,
    duration_ms: Annotated[int, Field(ge=300, le=10000, description="Hold duration in ms")] = 800,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Long-press at (x, y). Implemented as a 0-distance swipe."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_shell(f"input swipe {x} {y} {x} {y} {duration_ms}", timeout=15, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], **_diag(r)}
    return {"ok": True, "x": x, "y": y, "duration_ms": duration_ms}


# ============================================================
#                       KEYBOARD
# ============================================================

# Friendly key-name aliases -> Android KEYCODE_*
_KEY_ALIASES = {
    "back": "KEYCODE_BACK",
    "home": "KEYCODE_HOME",
    "menu": "KEYCODE_MENU",
    "recent": "KEYCODE_APP_SWITCH",
    "app_switch": "KEYCODE_APP_SWITCH",
    "power": "KEYCODE_POWER",
    "wake": "KEYCODE_WAKEUP",
    "sleep": "KEYCODE_SLEEP",
    "volume_up": "KEYCODE_VOLUME_UP",
    "volume_down": "KEYCODE_VOLUME_DOWN",
    "mute": "KEYCODE_VOLUME_MUTE",
    "enter": "KEYCODE_ENTER",
    "tab": "KEYCODE_TAB",
    "escape": "KEYCODE_ESCAPE",
    "del": "KEYCODE_DEL",
    "delete": "KEYCODE_DEL",
    "backspace": "KEYCODE_DEL",
    "space": "KEYCODE_SPACE",
    "search": "KEYCODE_SEARCH",
    "camera": "KEYCODE_CAMERA",
}


@mcp.tool
def press_key(
    key: Annotated[
        str,
        Field(description="Key name: back/home/menu/recent/power/wake/volume_up/volume_down/enter/tab/del/space/search/camera"),
    ],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Send a physical / system key to the device. Uses Android KeyEvent."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    code = _KEY_ALIASES.get(key.lower())
    if code is None:
        return {
            "ok": False,
            "error": f"unknown key '{key}'. Allowed: {sorted(_KEY_ALIASES.keys())}",
        }
    r = _adb_shell(f"input keyevent {code}", timeout=5, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], **_diag(r)}
    return {"ok": True, "key": key, "keycode": code}


@mcp.tool
def type_text(
    text: Annotated[str, Field(description="Text to type. Whitespace and special chars handled.")],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Type text into the currently focused input. Uses `adb shell input text`.

    NOTE: `adb input text` does NOT support newlines or all unicode. For
    Chinese / emoji / multiline, push to the device clipboard via `am
    broadcast` and paste -- not implemented in v0.4.0.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    # `input text` interprets some chars specially. Escape spaces and quotes.
    escaped = text.replace(" ", "%s").replace("'", "\\'").replace('"', '\\"')
    r = _adb_shell(f"input text '{escaped}'", timeout=15, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], **_diag(r)}
    return {"ok": True, "chars": len(text)}


# ============================================================
#                       APP MANAGEMENT
# ============================================================

@mcp.tool
def list_packages(
    filter_substring: Annotated[
        Optional[str],
        Field(description="Filter package names containing this substring; None = all"),
    ] = None,
    only_user: Annotated[bool, Field(description="Only third-party (non-system) packages")] = True,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """List installed app packages. `pm list packages`."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    flag = "-3" if only_user else ""
    r = _adb_shell(f"pm list packages {flag}".strip(), timeout=15, serial=serial)
    if r["returncode"] != 0:
        return {"error": r["stderr"], **_diag(r)}
    pkgs = []
    for ln in r["stdout"].splitlines():
        if ln.startswith("package:"):
            p = ln[len("package:"):].strip()
            if filter_substring is None or filter_substring in p:
                pkgs.append(p)
    return {"count": len(pkgs), "packages": pkgs}


@mcp.tool
def install_app(
    path: Annotated[str, Field(description="Absolute path to .apk on the HOST machine")],
    replace: Annotated[bool, Field(description="-r flag: replace existing")] = True,
    grant_runtime: Annotated[bool, Field(description="-g flag: grant all runtime permissions")] = False,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Install an APK from the host onto the device. `adb install`.

    Note: subprocess timeout is hard-capped at 25s (fastmcp transport limit).
    Large APKs (>~50MB on USB 2.0 / >~20MB wireless) may not finish in time —
    if you get `timed_out: true`, the install needs to be retried or split.
    Async install via start_process is planned.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    p = Path(path).expanduser()
    if not p.is_file():
        return {"ok": False, "error": f"apk not found: {path}"}
    args = ["install"]
    if replace:
        args.append("-r")
    if grant_runtime:
        args.append("-g")
    args.append(str(p))
    r = _adb_run(args, timeout=120, serial=serial)
    if r["returncode"] != 0 or "Success" not in r["stdout"]:
        return {"ok": False, "stdout": r["stdout"], "stderr": r["stderr"], **_diag(r)}
    return {"ok": True, "path": str(p)}


@mcp.tool
def uninstall_app(
    target: Annotated[str, Field(description="Package id, e.g. 'com.example.app'")],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Uninstall an app by package id. `adb uninstall`.

    Note: subprocess timeout is hard-capped at 25s (fastmcp transport limit).
    Typical uninstall is <5s; capped path is only a concern for very fragmented
    storage or very large apps. `timed_out: true` → retry.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_run(["uninstall", target], timeout=30, serial=serial)
    if r["returncode"] != 0 or "Success" not in r["stdout"]:
        return {"ok": False, "stdout": r["stdout"], "stderr": r["stderr"], **_diag(r)}
    return {"ok": True, "target": target}


@mcp.tool
def launch_app(
    target: Annotated[str, Field(description="Package id, e.g. 'com.android.settings'")],
    activity: Annotated[
        Optional[str],
        Field(description="Activity name (e.g. '.MainActivity'). None = use launcher intent."),
    ] = None,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Launch an app. With activity: `am start -n pkg/activity`. Without: `monkey -p pkg`."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    if activity:
        if not activity.startswith("."):
            am_component = f"{target}/{activity}"
        else:
            am_component = f"{target}/{target}{activity}"
        r = _adb_shell(f"am start -n {am_component}", timeout=15, serial=serial)
    else:
        r = _adb_shell(f"monkey -p {target} -c android.intent.category.LAUNCHER 1", timeout=15, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], "stdout": r["stdout"], **_diag(r)}
    return {"ok": True, "target": target, "stdout": r["stdout"][:500]}


@mcp.tool
def terminate_app(
    target: Annotated[str, Field(description="Package id to force-stop")],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Force-stop an app. `am force-stop`."""
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_shell(f"am force-stop {target}", timeout=10, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": r["stderr"], **_diag(r)}
    return {"ok": True, "target": target}


@mcp.tool
def current_app(
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Return the package name of the currently focused app on the device.

    Tries multiple dumpsys commands since the format varies across Android
    versions and OEM ROMs (EMUI, MIUI, OneUI, etc.).
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    import re
    pkg_pattern = re.compile(r"([a-zA-Z][\w.]+\.[\w.]+)/[\w.$]+")

    # Strategy 1: dumpsys window (compact, has mCurrentFocus near top)
    for cmd, key in [
        ("dumpsys window", "mCurrentFocus"),
        ("dumpsys window", "mFocusedApp"),
        ("dumpsys activity activities", "mResumedActivity"),
        ("dumpsys activity activities", "topResumedActivity"),
        ("dumpsys window windows", "mCurrentFocus"),
    ]:
        r = _adb_shell(cmd, timeout=10, serial=serial)
        if r["returncode"] != 0:
            continue
        for ln in r["stdout"].splitlines():
            if key in ln:
                m = pkg_pattern.search(ln)
                if m:
                    return {"package": m.group(1), "via": f"{cmd} -> {key}", "raw": ln.strip()}

    return {"error": "could not find current focus", "tried": "dumpsys window/activity"}


# ============================================================
#                       SHELL
# ============================================================

@mcp.tool
def run_shell(
    script: Annotated[str, Field(description="Shell command to run ON the device")],
    timeout: Annotated[int, Field(ge=1, le=25, description="Seconds; hard-capped to 25 — fastmcp transport dies past ~30s (jlowin/fastmcp#823)")] = 25,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Run an arbitrary shell command on the Android device. Max 25s — for long jobs push to background then poll.

    Useful for `getprop`, `dumpsys`, `pm`, `am`, `settings`, `cmd`, etc.
    Output > 100KB is truncated.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    r = _adb_shell(script, timeout=min(timeout, 25), serial=serial)
    out = r["stdout"]
    if len(out) > 100_000:
        out = out[:100_000] + f"\n[... truncated, total {len(r['stdout'])} chars]"
    return {
        "returncode": r["returncode"],
        "stdout": out,
        "stderr": r["stderr"],
        **_diag(r),
    }


# ============================================================
#                  HOST <-> DEVICE FILE TRANSFER
# ============================================================

@mcp.tool
def push_file(
    host_path: Annotated[str, Field(description="Absolute path on the HOST")],
    device_path: Annotated[str, Field(description="Destination path on the DEVICE (e.g. /sdcard/foo.txt)")],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Copy a file from host to device. `adb push`.

    Note: subprocess timeout is hard-capped at 25s (fastmcp transport limit).
    On USB 2.0 (~30MB/s) this covers files up to ~500MB; wireless ADB is much
    slower (~3-10MB/s) so practical limit is ~50-100MB. `timed_out: true` →
    split the file or copy it via the device's filesystem out-of-band first.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    h = Path(host_path).expanduser()
    if not h.is_file():
        return {"ok": False, "error": f"host file not found: {host_path}"}
    r = _adb_run(["push", str(h), device_path], timeout=300, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "stdout": r["stdout"], "stderr": r["stderr"], **_diag(r)}
    return {"ok": True, "host": str(h), "device": device_path, "size": h.stat().st_size}


@mcp.tool
def pull_file(
    device_path: Annotated[str, Field(description="Source path on the DEVICE")],
    host_path: Annotated[str, Field(description="Destination path on the HOST (parent dir must exist)")],
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Copy a file from device to host. `adb pull`.

    Note: subprocess timeout is hard-capped at 25s (fastmcp transport limit).
    Same file-size envelope as push_file. `timed_out: true` → split, or pull
    over USB instead of wireless if size matters.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    h = Path(host_path).expanduser()
    h.parent.mkdir(parents=True, exist_ok=True)
    r = _adb_run(["pull", device_path, str(h)], timeout=300, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "stdout": r["stdout"], "stderr": r["stderr"], **_diag(r)}
    return {
        "ok": True,
        "device": device_path,
        "host": str(h),
        "size": h.stat().st_size if h.exists() else None,
    }


# ============================================================
#                    UI ELEMENT INTROSPECTION
# ============================================================

def _parse_bounds(s: str) -> Optional[list[int]]:
    """Parse uiautomator bounds string '[x1,y1][x2,y2]' → [x1,y1,x2,y2]."""
    import re
    m = re.match(r"\[(-?\d+),(-?\d+)\]\[(-?\d+),(-?\d+)\]", s)
    if not m:
        return None
    return [int(m.group(i)) for i in (1, 2, 3, 4)]


def _walk_xml(node, depth: int, out: list, max_depth: int):
    """Flatten uiautomator XML tree into a list of element dicts.

    Each element gets a center (x, y) computed from its bounds rectangle so
    callers can tap it directly without parsing bounds themselves.
    """
    if depth > max_depth:
        return
    attrs = node.attrib
    bounds = _parse_bounds(attrs.get("bounds", "")) if attrs.get("bounds") else None
    if bounds:
        x1, y1, x2, y2 = bounds
        center = [(x1 + x2) // 2, (y1 + y2) // 2]
        width, height = x2 - x1, y2 - y1
    else:
        center = None
        width = height = 0
    # Skip the root <hierarchy> wrapper element (no class attr).
    if attrs.get("class"):
        out.append({
            "class": attrs.get("class", ""),
            "text": attrs.get("text", ""),
            "resource_id": attrs.get("resource-id", ""),
            "content_desc": attrs.get("content-desc", ""),
            "package": attrs.get("package", ""),
            "bounds": bounds,
            "center": center,
            "width": width,
            "height": height,
            "clickable": attrs.get("clickable") == "true",
            "enabled": attrs.get("enabled") == "true",
            "focused": attrs.get("focused") == "true",
            "scrollable": attrs.get("scrollable") == "true",
            "depth": depth,
        })
    for child in list(node):
        _walk_xml(child, depth + 1, out, max_depth)


@mcp.tool
def dump_ui(
    max_depth: Annotated[int, Field(ge=1, le=20, description="Max tree depth to walk")] = 12,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Dump the current screen's UI element tree via `uiautomator dump`.

    Returns a flat list of elements with:
      - class, text, resource_id, content_desc, package
      - bounds [x1,y1,x2,y2], center [x,y], width, height
      - clickable / enabled / focused / scrollable flags
      - depth in tree

    Use the center coords to tap() the element without computing bounds yourself.
    Use find_elements() for filtering, or tap_element() for the common
    find-then-tap path.

    Some apps (games, Flutter canvas, secured banking apps) don't expose
    uiautomator elements — fall back to take_screenshot + tap(x, y) for those.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    # 1. uiautomator dump on device → /sdcard/window_dump.xml
    dump_path_device = "/sdcard/window_dump.xml"
    r = _adb_shell(f"uiautomator dump {dump_path_device}", timeout=15, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": "uiautomator dump failed", "stderr": r["stderr"]}

    # 2. cat the XML back (avoids needing a host tmp file)
    r = _adb_shell(f"cat {dump_path_device}", timeout=10, capture_bytes=True, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": "cat dump failed", "stderr": r["stderr"]}
    # _adb_run(capture_bytes=True) puts raw bytes in "stdout_bytes" and sets
    # "stdout" to "".  Reading r["stdout"] gave an empty string, which then
    # failed XML parsing with "no element found at line 1 col 0".
    xml_bytes = r.get("stdout_bytes", b"")
    if not xml_bytes:
        return {"ok": False, "error": "empty UI dump (file present on device but adb pull returned 0 bytes)"}

    # 3. parse + flatten
    import xml.etree.ElementTree as ET
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError as e:
        return {"ok": False, "error": f"XML parse failed: {e}"}

    elements: list[dict] = []
    _walk_xml(root, 0, elements, max_depth)

    return {"ok": True, "count": len(elements), "elements": elements}


@mcp.tool
def find_elements(
    text: Annotated[Optional[str], Field(description="Substring-match Element.text")] = None,
    resource_id: Annotated[Optional[str], Field(description="Substring-match resource_id")] = None,
    content_desc: Annotated[Optional[str], Field(description="Substring-match content_desc (a11y label)")] = None,
    class_name: Annotated[Optional[str], Field(description="Substring-match class (e.g. 'android.widget.Button')")] = None,
    clickable_only: Annotated[bool, Field(description="Only return clickable=true elements")] = False,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Find UI elements matching all provided filters (substring match, AND logic).

    At least one filter MUST be provided.  Returns same element shape as
    dump_ui().

    Example:
        find_elements(content_desc="拍照")   # → camera shutter button
        find_elements(resource_id="shutter_button", clickable_only=True)
    """
    if not any([text, resource_id, content_desc, class_name]):
        return {"ok": False, "error": "at least one filter required"}

    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    dump = dump_ui(device=serial)
    if not dump.get("ok"):
        return dump

    def matches(e: dict) -> bool:
        if text and text not in e["text"]:
            return False
        if resource_id and resource_id not in e["resource_id"]:
            return False
        if content_desc and content_desc not in e["content_desc"]:
            return False
        if class_name and class_name not in e["class"]:
            return False
        if clickable_only and not e["clickable"]:
            return False
        return True

    matches_list = [e for e in dump["elements"] if matches(e)]
    return {"ok": True, "count": len(matches_list), "elements": matches_list}


@mcp.tool
def tap_element(
    text: Annotated[Optional[str], Field(description="Substring-match Element.text")] = None,
    resource_id: Annotated[Optional[str], Field(description="Substring-match resource_id")] = None,
    content_desc: Annotated[Optional[str], Field(description="Substring-match content_desc")] = None,
    class_name: Annotated[Optional[str], Field(description="Substring-match class")] = None,
    nth: Annotated[int, Field(ge=0, description="If multiple match, tap the nth (0-indexed)")] = 0,
    device: Annotated[str | None, Field(description="serial or alias; omit if only 1 phone or you've set a default")] = None,
    ctx: Context = None,
) -> dict:
    """Find an element by filter and tap its center.

    The element-driven equivalent of tap(x, y), but resilient to screen
    resolution / layout changes since it looks up by semantic attributes.

    Errors out if no element matches OR nth is out of range — so the agent
    sees a clear failure instead of tapping nothing.
    """
    serial = _resolve_device(device, _get_session_default(ctx))
    _state_registry.touch(serial)
    found = find_elements(
        text=text,
        resource_id=resource_id,
        content_desc=content_desc,
        class_name=class_name,
        clickable_only=False,
        device=serial,
    )
    if not found.get("ok"):
        return found
    matches_list = found["elements"]
    if not matches_list:
        return {"ok": False, "error": "no element matched the filter"}
    if nth >= len(matches_list):
        return {"ok": False, "error": f"only {len(matches_list)} element(s) matched, requested nth={nth}"}

    el = matches_list[nth]
    if not el["center"]:
        return {"ok": False, "error": "matched element has no bounds — cannot tap"}

    cx, cy = el["center"]
    r = _adb_shell(f"input tap {cx} {cy}", timeout=10, serial=serial)
    if r["returncode"] != 0:
        return {"ok": False, "error": "input tap failed", "stderr": r["stderr"]}

    return {"ok": True, "tapped_at": [cx, cy], "element": el, "total_matches": len(matches_list)}


# ============================================================
#                       ENTRY POINT
# ============================================================

if __name__ == "__main__":
    # Line-buffer stdout/stderr so startup banner + status lines flush into
    # redirected log files in real time (block-buffered default would only
    # flush on exit, making `python server.py > log 2>&1` appear "silent"
    # until the server crashes).
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(line_buffering=True)
        sys.stderr.reconfigure(line_buffering=True)
    print(f"android-device MCP server starting")
    print(f"  adb       = {_ADB}")
    print(f"  host      = {host_platform.system()} {host_platform.release()}")
    try:
        detected = _detect_devices()
        if not detected:
            print(f"  devices   = NONE")
            print(f"  WARNING: server will start but tools will fail until a device appears.")
        else:
            overrides = _load_alias_overrides()
            aliases = resolve_aliases(detected, overrides)
            print(f"  devices   = {len(detected)} attached")
            for d in detected:
                alias = aliases.get(d.serial, "?")
                print(f"    - {alias}  ({d.serial}, {d.brand or '?'} {d.model or '?'})")
    except Exception as e:
        print(f"  devices   = ERROR  ({e})")
        print(f"  WARNING: server will start but tools may fail until adb is healthy.")
    # Transport: streamable-http (FastMCP "http" alias). Migrated from
    # SSE for the same reason as mac-device / win-device: long tool calls
    # broke SSE keep-alive and yielded -32602 forever after.
    # Endpoint: http://<host>:8768/mcp  (was /sse)
    print(f"  transport = http (streamable) on 0.0.0.0:8768/mcp")
    mcp.run(transport="http", host="0.0.0.0", port=8768)
